### PR TITLE
Externalize & update unmodified deps

### PR DESCRIPTION
**Pull request by kacperzuk-neti**
Removes unmodified deps from our repo, pulls them using Cargo. Uses polkadot-0.9.33 branch for deps. Also merges changes to things we've modified.

Identified breaking changes in relevant APIs:

- identity.provideJudgement now takes hash of IdentityInfo as additional argument: https://paritytech.github.io/substrate/master/pallet_identity/pallet/struct.Pallet.html#method.provide_judgement
- democracy.propose now takes Bounded instead of plain hash https://paritytech.github.io/substrate/master/pallet_democracy/pallet/struct.Pallet.html#method.propose
- all preimige stuff moved from democracy to preimage pallet: https://paritytech.github.io/substrate/master/pallet_preimage/index.html
- when adding validator, I needed to first setup account and then call session.setKeys. Otherwise I got "NoAssociatedValidatorId" error.
- ...?

99% of changes are either deletes due to externalizing deps or modifications pulled from upstream. To make CR easier, here's list of files that were modified both in this PR and in our previous LL changes:

- bin/node/cli/Cargo.toml
- bin/node/cli/src/chain_spec.rs
- bin/node/runtime/Cargo.toml
- bin/node/runtime/src/lib.rs
- Cargo.lock
- Cargo.toml
- frame/democracy/Cargo.toml
- frame/democracy/src/lib.rs
- frame/elections-phragmen/Cargo.toml
- frame/elections-phragmen/src/lib.rs
- frame/identity/src/benchmarking.rs
- frame/identity/src/lib.rs
- frame/identity/src/types.rs
- frame/liberland-legislation/Cargo.toml
- frame/liberland-legislation/src/lib.rs
- frame/llm/Cargo.toml
- frame/llm/src/lib.rs

Note the `[patch."https://github.com/paritytech/substrate"]` section of workspace's `Cargo.toml`. This is required to make sure that external deps (like `node-executor`) use our versions of deps where necessary (like runtime).

### CODE REVIEW

**Comment by flipchan** [comment]
new dependency needed:
```
apt install -y protobuf-compiler
```

**Comment by flipchan** [comment]
need to bump up the Cargo package version in the current pallets:  
frame/democracy/Cargo.toml
frame/elections-phragmen/Cargo.toml
frame/identity/src/lib.rs
frame/liberland-legislation/src/lib.rs
frame/llm/Cargo.toml

**Comment by flipchan** [comment]
Can we rename "kitchensink-runtime" to liberland runtime?

**Comment by kacperzuk-neti** [comment]
> need to bump up the Cargo package version in the current pallets:
frame/democracy/Cargo.toml
frame/elections-phragmen/Cargo.toml
frame/identity/src/lib.rs
frame/liberland-legislation/src/lib.rs
frame/llm/Cargo.toml

Huh, upstream doesn't seem to care about pallet versioning, they keep 4.0.0-dev even for breaking changes, weird. However, I would like to keep it the same as upstream for democracy/elections/identity, to prevent confusion when comparing in the future. Do you have any specific reason for diverging?

I'll bump llm and liberland.

**Comment by kacperzuk-neti** [comment]
> Can we rename "kitchensink-runtime" to liberland runtime?

We could, but we'd have to modify a bunch of files we don't touch currently + bring some dependencies back into our repo (`node-executor`), I don't think it's worth it just for naming sake.

**Comment by flipchan** [comment]
> > need to bump up the Cargo package version in the current pallets:
> > frame/democracy/Cargo.toml
> > frame/elections-phragmen/Cargo.toml
> > frame/identity/src/lib.rs
> > frame/liberland-legislation/src/lib.rs
> > frame/llm/Cargo.toml
> 
> Huh, upstream doesn't seem to care about pallet versioning, they keep 4.0.0-dev even for breaking changes, weird. However, I would like to keep it the same as upstream for democracy/elections/identity, to prevent confusion when comparing in the future. Do you have any specific reason for diverging?
> 
> I'll bump llm and liberland.

If depencies has changed in the pallets, then they need to get bumped, if no dependency version has changed, leave it

**Comment by kacperzuk-neti** [comment]
> If depencies has changed in the pallets, then they need to get bumped, if no dependency version has changed, leave it

Okay, cool. Those that had changed were bumped.

**Comment by flipchan** [comment]
let's bump up scale-codec to 3.2.1
local decencies have:
```
 grep -r parity-scale-codec | grep "version"
frame/democracy/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
frame/identity/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
frame/llm/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
frame/elections-phragmen/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
```

remote depencies:
```
cargo tree -e features | grep codec |uniq | grep 3
│   │   │   ├── parity-scale-codec v3.1.3
│   │   │   │   ├── parity-scale-codec-derive v3.1.3 (proc-macro)
│   │   │   │   │   │   │       ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   │       │   └── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   │           └── parity-scale-codec-derive v3.1.3 (proc-macro) (*)
│   │   │   │   │   │       │   │   ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   └── parity-scale-codec v3.1.3 (*)
│   │   │   │   │       │   ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
│   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
│   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
│   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
│   ├── parity-scale-codec v3.1.3 (*)


```

**Comment by kacperzuk-neti** [comment]
> let's bump up scale-codec to 3.2.1 local decencies have:
> 
> ```
>  grep -r parity-scale-codec | grep "version"
> frame/democracy/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
> frame/identity/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
> frame/llm/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
> frame/elections-phragmen/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
> ```
> 
> remote depencies:
> 
> ```
> cargo tree -e features | grep codec |uniq | grep 3
> │   │   │   ├── parity-scale-codec v3.1.3
> │   │   │   │   ├── parity-scale-codec-derive v3.1.3 (proc-macro)
> │   │   │   │   │   │   │       ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   │       │   └── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   │           └── parity-scale-codec-derive v3.1.3 (proc-macro) (*)
> │   │   │   │   │   │       │   │   ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   └── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │       │   ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> │   ├── parity-scale-codec v3.1.3 (*)
> ```

Specifications in Cargo.toml follow semver, so `3.0.0` in our Cargo.tomls match `3.1.3`. What's more, see that remote deps also have `3.0.0` in their Cargo.tomls: https://github.com/paritytech/substrate/blob/master/frame/assets/Cargo.toml#L16 .
Best practice is to keep `3.0.0` in Cargo.toml and use `Cargo.lock` to match specific version, which is already done. Updating `Cargo.toml` for each minor/patch version is unnecessary.

**Comment by flipchan** [comment]
> > let's bump up scale-codec to 3.2.1 local decencies have:
> > ```
> >  grep -r parity-scale-codec | grep "version"
> > frame/democracy/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
> > frame/identity/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
> > frame/llm/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
> > frame/elections-phragmen/Cargo.toml:codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > remote depencies:
> > ```
> > cargo tree -e features | grep codec |uniq | grep 3
> > │   │   │   ├── parity-scale-codec v3.1.3
> > │   │   │   │   ├── parity-scale-codec-derive v3.1.3 (proc-macro)
> > │   │   │   │   │   │   │       ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   │       │   └── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   │           └── parity-scale-codec-derive v3.1.3 (proc-macro) (*)
> > │   │   │   │   │   │       │   │   ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   └── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │       │   ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │       │   │   └── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> > │   │   │   │   │   │   ├── parity-scale-codec v3.1.3 (*)
> > │   ├── parity-scale-codec v3.1.3 (*)
> > ```
> 
> Specifications in Cargo.toml follow semver, so `3.0.0` in our Cargo.tomls match `3.1.3`. What's more, see that remote deps also have `3.0.0` in their Cargo.tomls: https://github.com/paritytech/substrate/blob/master/frame/assets/Cargo.toml#L16 . Best practice is to keep `3.0.0` in Cargo.toml and use `Cargo.lock` to match specific version, which is already done. Updating `Cargo.toml` for each minor/patch version is unnecessary.
> 
> EDIT: just to be clear, local deps also use 3.1.3 even though 3.0.0 is specified in Cargo.toml (as they match due to semver rules).

good catch

https://github.com/paritytech/substrate/blob/polkadot-v0.9.33/frame/assets/Cargo.toml#L16

**Comment by kacperzuk-neti** [comment]
@flipchan @DorianSternVukotic Is it ready to be merged or are there any other concerns?

**Pull request merged**
